app:
  build: .
  tty: true
  stdin_open: true
  volumes:
    - .:/app
  ports:
    - 4040:4040

web:
  extends: app
  command: bash -c "while [ true ]; do sleep 10; done"
  container_name: web
  environment:
    - USER
    - USERNAME
    - MIX_ENV=dev
    - PG_HOST=db
    - PG_USERNAME=postgres
    - PG_PASSWORD=postgres
  links:
    - db

tests:
  extends: app
  command: mix do coveralls
  environment:
    - USER
    - USERNAME
    - MIX_ENV=test
    - PG_HOST=db
    - PG_USERNAME=postgres
    - PG_PASSWORD=postgres
  links:
    - db

db:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres